export const TEMPLATES_SAVE_EXPORT_TEMPLATE = "TEMPLATES_SAVE_EXPORT_TEMPLATE";
export const TEMPLATES_UPDATE_CURRENT_TEMPLATE =
  "TEMPLATES_UPDATE_CURRENT_TEMPLATE";
export const TEMPLATES_LOAD_TEMPLATES = "TEMPLATES_LOAD_TEMPLATES";
export const RESET_TEMPLATE = "EXPORT_CONFIG_RESET";
