export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const CLEAR_ALL_NOTIFICATIONS = "CLEAR_ALL_NOTIFICATIONS";
export const CURRENT_USER_RECIEVED = "CURRENT_USER_RECIEVED";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
export const ART_GALLERY_RECIEVED = "ART_GALLERY_RECIEVED";
